### ISSUE TITLE
What is the format of input data(edge_list)?

### ISSUE THREAD

**Issue by sunshine2sunflower** [razrLeLe/fastwalk#1]
My group has 30000+ nodes and 3000000+ edges, why it just takes a few minutes to finish the walk?
--delimiter space --p 0.25 --q 1 --walk_length=5 --num_walks=3 --workers=20 --max_nodes 50000 --max_edges 50000

**Comment by razrLeLe** [comment]
```
node1 node2 [edge_weight]
node2 node3 [edge_weight]
```
The delimiter is either tab or space, specified by `--delimiter`;
edge_weight is 1.0 as default.
