### ISSUE TITLE
the walk result dimension seems to be incorrect

### ISSUE THREAD

**Issue by iosmers** [razrLeLe/fastwalk#2]
Hi, @razrLeLe , I use your code to run an input graph which data is formated by edgelists, it looks like this:

>  1 176
1 233
1 283
1 371
1 394
1 446
1 585
1 645
1 667
1 696
...
I use command :`./fastwalk --edge_list src/edges.txt --output edgestxt.out --walk_length=80 --num_walks=10 --workers=20 --max_nodes=50000 --max_edges=100000 --p=10 --q=0.01
`
As far as I know, the result dimension should be (V*num_walks)x(num_walks), V is the size of vertex.However, both the row and column of result I get are wrong, So, i don't understand the output mean

**Comment by razrLeLe** [comment]
The result's shape should be (V*num_walks, walk_length), what's the shape you got?

**Comment by iosmers** [comment]
The row should be 7115*10, the column should be 80, but i get 194749 * 2. 
And, I find your vertex count is not correct,The vertex of my graph is 7115 , howerver, your code says 8491,I don't konw why. The edges number is correct.

**Comment by razrLeLe** [comment]
Can you offer some data to debug?

**Comment by iosmers** [comment]
The  link: https://pan.baidu.com/s/13Hua7ZtRVS_XC2YSMFQTrA ,and password: be5h

**Comment by razrLeLe** [comment]
There are Windows newline symbols in your input data, which results in the incorrect output, I will add string trimming during loading graph in the future, before that please preprocess the input data yourself.

You can use sed to remove those symbols first:

`cat edges.txt | sed -e 's/\r//' > edges_trimmed.txt`

it shows that there are 10312 vertexes:

```
~/workspace/fastwalk(master*) » cat edges_trimmed.txt | awk '{printf("%s\n%s\n", $1, $2);}' | sort -u | wc -l

10312
```
and the program will output as expection:

```
~/workspace/fastwalk(master*) » ./fastwalk --edge_list edges_trimmed.txt --output edges_out.txt --delimiter space --p 10 --q 0.01 --max_nodes 50000 --max_edges 50000 --workers 4
[2021-02-06 13:38:45] Loading file: edges_trimmed.txt
[2021-02-06 13:38:45] Done reading edgelist files, starting to build graph...
[2021-02-06 13:38:46] Done building graph.
[2021-02-06 13:38:46] Graph node num: 10312 edge num: 333983
[2021-02-06 13:38:46] Graph loaded.
[2021-02-06 13:38:47] Starting to walk...
[2021-02-06 13:38:47] Done feeding nodes.
[2021-02-06 13:39:12] All done.
```

Notice that the input data is loaded as directed graph, which means there can be vertex whose out-degree is 0, the walk will stop when reached those vertexes, so each row may have columns less than walk_length.

**Comment by iosmers** [comment]
OK,thanks.
